<?php

return array(
	'version' => '0.9.3',
	'pgcache.file.nfs' => false,
	'minify.file.nfs' => false,
	'dbcache.file.locking' => false,
	'objectcache.file.locking' => false,
	'pgcache.file.locking' => false,
	'minify.file.locking' => false,
	'dbcache.reject.logged' => true,
	'dbcache.lifetime' => 180,
	'dbcache.file.gc' => 3600,
	'dbcache.reject.uri' => array(
		0 => '',
	),
	'dbcache.reject.sql' => array(
		0 => 'gdsr_',
		1 => 'wp_rg_',
		2 => '_wc_session_',
	),
	'dbcache.reject.words' => array(
		0 => '^\\s*insert\\b',
		1 => '^\\s*delete\\b',
		2 => '^\\s*update\\b',
		3 => '^\\s*replace\\b',
		4 => '^\\s*create\\b',
		5 => '^\\s*alter\\b',
		6 => '^\\s*show\\b',
		7 => '^\\s*set\\b',
		8 => '\\bautoload\\s+=\\s+\'yes\'',
		9 => '\\bsql_calc_found_rows\\b',
		10 => '\\bfound_rows\\(\\)',
		11 => '\\bw3tc_request_data\\b',
	),
	'notes.need_empty_pgcache' => false,
	'notes.plugins_updated' => false,
	'pgcache.enabled' => true,
	'pgcache.engine' => 'apc',
	'dbcache.enabled' => true,
	'dbcache.engine' => 'apc',
	'objectcache.enabled' => true,
	'objectcache.engine' => 'apc',
	'cdn.enabled' => false,
	'cdn.engine' => 'maxcdn',
	'varnish.enabled' => false,
	'varnish.servers' => array(
		0 => '',
	),
	'cloudflare.enabled' => false,
	'cloudflare.email' => '',
	'cloudflare.key' => '',
	'cloudflare.zone' => '',
	'widget.pagespeed.enabled' => true,
	'widget.pagespeed.key' => '',
	'config.check' => true,
	'pgcache.debug' => true,
	'dbcache.debug' => true,
	'cdn.debug' => false,
	'objectcache.debug' => true,
);